[package]
name = "kvs"
version = "0.1.0"
authors = ["LOU Xun <aquarhead@ela.build>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
structopt = "0.3"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
